### PR TITLE
[#2746] Fix assertIsEmpty.

### PR DESCRIPTION
**Pull request by adiroiban**
Problem
======

assertIsEmpty fails when checking for a non empty tupple

Why we got this
============

no tests
bad practice for string formating not forced in a tupple

Changes
=======

fix and write tests.

How to test
=========

reviewers: @alibotean 

check that changes make sense
version released as needed in compat.

Thanks!

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by alibotean** [comment]
changes-approved

**Comment by adiroiban** [comment]
I have also found another error in empirical and fixed it in this branch... as I was lazy. Please see latest diff. Just to let you know. Thanks!
needs-review

**Comment by alibotean** [comment]
K, thx.

changes-approved

**Pull request closed without merging**
